export const WORKOUT_TEMPLATES = {
  push: {
    name: 'Push Day — Hypertrophy Focus',
    category: 'push',
    focus: 'Chest, Shoulders & Triceps',
    estimated_duration: 70,
    titan_note: 'A balanced hypertrophy-focused push session targeting chest thickness, shoulder width, and tricep mass.',
    exercises: [
      { name: 'Barbell Bench Press', muscle_group: 'chest', target_sets: 4, target_reps: 7 },
      { name: 'Incline Dumbbell Press', muscle_group: 'chest', target_sets: 3, target_reps: 9 },
      { name: 'Seated Dumbbell Shoulder Press', muscle_group: 'shoulders', target_sets: 3, target_reps: 9 },
      { name: 'Cable Lateral Raise', muscle_group: 'shoulders', target_sets: 3, target_reps: 13 },
      { name: 'Triceps Rope Pushdown', muscle_group: 'arms', target_sets: 3, target_reps: 11 },
      { name: 'Overhead Cable Triceps Extension', muscle_group: 'arms', target_sets: 3, target_reps: 11 },
    ],
  },
  pull: {
    name: 'Pull Day — Back & Biceps Focus',
    category: 'pull',
    focus: 'Back, Rear Delts & Biceps',
    estimated_duration: 65,
    titan_note: 'This pull session prioritizes lat development and upper-back thickness, finishing with direct bicep work.',
    exercises: [
      { name: 'Pull-Ups or Lat Pulldown', muscle_group: 'back', target_sets: 4, target_reps: 8, target_reps_label: '6-10' },
      { name: 'Barbell Row', muscle_group: 'back', target_sets: 4, target_reps: 7 },
      { name: 'Chest-Supported Row', muscle_group: 'back', target_sets: 3, target_reps: 9 },
      { name: 'Seated Cable Row', muscle_group: 'back', target_sets: 3, target_reps: 11 },
      { name: 'Face Pull', muscle_group: 'shoulders', target_sets: 3, target_reps: 13 },
      { name: 'Dumbbell Curl', muscle_group: 'arms', target_sets: 3, target_reps: 11 },
    ],
  },
  legs: {
    name: 'Leg Day — Lower Body Strength & Size',
    category: 'legs',
    focus: 'Quads, Hamstrings & Glutes',
    estimated_duration: 75,
    titan_note: 'A complete lower body session built around compound strength movements, finishing with isolation work for full quad and hamstring development.',
    exercises: [
      { name: 'Barbell Squat or Hack Squat', muscle_group: 'legs', target_sets: 4, target_reps: 7 },
      { name: 'Romanian Deadlift', muscle_group: 'legs', target_sets: 3, target_reps: 9 },
      { name: 'Leg Press', muscle_group: 'legs', target_sets: 3, target_reps: 11 },
      { name: 'Seated Leg Curl', muscle_group: 'legs', target_sets: 3, target_reps: 11 },
      { name: 'Leg Extension', muscle_group: 'legs', target_sets: 3, target_reps: 13 },
      { name: 'Standing Calf Raise', muscle_group: 'legs', target_sets: 4, target_reps: 12 },
    ],
  },
  chest: {
    name: 'Chest Day — Growth Focus',
    category: 'chest',
    focus: 'Chest Hypertrophy',
    estimated_duration: 60,
    titan_note: 'This chest session combines heavy compound pressing with isolation cable work to maximize chest development from all angles.',
    exercises: [
      { name: 'Incline Dumbbell Press', muscle_group: 'chest', target_sets: 4, target_reps: 8 },
      { name: 'Flat Barbell Bench Press', muscle_group: 'chest', target_sets: 4, target_reps: 6 },
      { name: 'Pec Deck Fly', muscle_group: 'chest', target_sets: 3, target_reps: 12 },
      { name: 'Machine Chest Press', muscle_group: 'chest', target_sets: 3, target_reps: 10 },
      { name: 'High Cable Fly', muscle_group: 'chest', target_sets: 3, target_reps: 13 },
    ],
  },
  back: {
    name: 'Back Day — Width & Thickness',
    category: 'back',
    focus: 'Lat Width & Upper Back Thickness',
    estimated_duration: 65,
    titan_note: 'This back day focuses on building wide lats and a thick upper back using vertical and horizontal pulling patterns.',
    exercises: [
      { name: 'Lat Pulldown', muscle_group: 'back', target_sets: 4, target_reps: 10 },
      { name: 'Barbell Row', muscle_group: 'back', target_sets: 4, target_reps: 7 },
      { name: 'Chest-Supported Row', muscle_group: 'back', target_sets: 3, target_reps: 9 },
      { name: 'Single-Arm Dumbbell Row', muscle_group: 'back', target_sets: 3, target_reps: 11 },
      { name: 'Straight-Arm Pulldown', muscle_group: 'back', target_sets: 3, target_reps: 13 },
    ],
  },
  shoulders: {
    name: 'Shoulders Day — Delts Focus',
    category: 'shoulders',
    focus: 'Anterior, Lateral & Posterior Delts',
    estimated_duration: 55,
    titan_note: 'This shoulder session builds round, capped delts by targeting all three delt heads with pressing, lateral, and rear delt work.',
    exercises: [
      { name: 'Seated Dumbbell Shoulder Press', muscle_group: 'shoulders', target_sets: 4, target_reps: 8 },
      { name: 'Cable Lateral Raise', muscle_group: 'shoulders', target_sets: 4, target_reps: 13 },
      { name: 'Machine Lateral Raise', muscle_group: 'shoulders', target_sets: 3, target_reps: 13 },
      { name: 'Reverse Pec Deck', muscle_group: 'shoulders', target_sets: 3, target_reps: 13 },
      { name: 'Dumbbell Front Raise', muscle_group: 'shoulders', target_sets: 3, target_reps: 11 },
    ],
  },
  arms: {
    name: 'Arms Day — Biceps & Triceps',
    category: 'arms',
    focus: 'Biceps & Triceps',
    estimated_duration: 55,
    titan_note: 'A dedicated arm day hitting biceps and triceps with equal volume to build size and definition from every angle.',
    exercises: [
      { name: 'EZ-Bar Curl', muscle_group: 'arms', target_sets: 3, target_reps: 9 },
      { name: 'Incline Dumbbell Curl', muscle_group: 'arms', target_sets: 3, target_reps: 11 },
      { name: 'Hammer Curl', muscle_group: 'arms', target_sets: 3, target_reps: 11 },
      { name: 'Close-Grip Bench Press', muscle_group: 'arms', target_sets: 3, target_reps: 7 },
      { name: 'Rope Pushdown', muscle_group: 'arms', target_sets: 3, target_reps: 11 },
      { name: 'Overhead Cable Extension', muscle_group: 'arms', target_sets: 3, target_reps: 11 },
    ],
  },
  glutes: {
    name: 'Glutes & Hamstrings — Shape and Strength',
    category: 'glutes',
    focus: 'Glutes, Hamstrings & Posterior Chain',
    estimated_duration: 65,
    titan_note: 'This glute and hamstring day prioritizes hip thrusts, RDLs, and posterior-chain development for strength and shape.',
    exercises: [
      { name: 'Barbell Hip Thrust', muscle_group: 'glutes', target_sets: 4, target_reps: 9 },
      { name: 'Romanian Deadlift', muscle_group: 'legs', target_sets: 4, target_reps: 9 },
      { name: 'Bulgarian Split Squat', muscle_group: 'legs', target_sets: 3, target_reps: 9, target_reps_label: '8-10/side' },
      { name: 'Seated or Lying Hamstring Curl', muscle_group: 'legs', target_sets: 3, target_reps: 11 },
      { name: 'Cable Kickback', muscle_group: 'glutes', target_sets: 3, target_reps: 13 },
      { name: 'Hip Abduction Machine', muscle_group: 'glutes', target_sets: 3, target_reps: 15 },
    ],
  },
  upper_body: {
    name: 'Upper Body — Balanced Strength & Size',
    category: 'upper_body',
    focus: 'Chest, Back, Shoulders & Arms',
    estimated_duration: 65,
    titan_note: 'A balanced upper-body session training push and pull movements together for efficient total upper-body development.',
    exercises: [
      { name: 'Barbell Bench Press', muscle_group: 'chest', target_sets: 3, target_reps: 7 },
      { name: 'Lat Pulldown', muscle_group: 'back', target_sets: 3, target_reps: 9 },
      { name: 'Seated Dumbbell Shoulder Press', muscle_group: 'shoulders', target_sets: 3, target_reps: 9 },
      { name: 'Chest-Supported Row', muscle_group: 'back', target_sets: 3, target_reps: 9 },
      { name: 'Cable Lateral Raise', muscle_group: 'shoulders', target_sets: 3, target_reps: 13 },
      { name: 'Rope Pushdown or Dumbbell Curl', muscle_group: 'arms', target_sets: 3, target_reps: 11, target_sets_label: '2-3' },
    ],
  },
  lower_body: {
    name: 'Lower Body — Complete Leg Focus',
    category: 'lower_body',
    focus: 'Quads, Hamstrings, Glutes & Calves',
    estimated_duration: 70,
    titan_note: 'A complete lower body session covering all major leg muscles with squats, hinges, and isolation work.',
    exercises: [
      { name: 'Squat or Hack Squat', muscle_group: 'legs', target_sets: 4, target_reps: 7 },
      { name: 'Romanian Deadlift', muscle_group: 'legs', target_sets: 3, target_reps: 9 },
      { name: 'Leg Press', muscle_group: 'legs', target_sets: 3, target_reps: 11 },
      { name: 'Leg Curl', muscle_group: 'legs', target_sets: 3, target_reps: 11 },
      { name: 'Walking Lunges', muscle_group: 'legs', target_sets: 3, target_reps: 10, target_sets_label: '2-3', target_reps_label: '10 steps/leg' },
      { name: 'Calf Raise', muscle_group: 'legs', target_sets: 4, target_reps: 13 },
    ],
  },
  full_body: {
    name: 'Full Body — Efficient Total-Body Session',
    category: 'full_body',
    focus: 'Full Body Compound Training',
    estimated_duration: 60,
    titan_note: 'An efficient full-body session using compound movements to train every major muscle group in one workout.',
    exercises: [
      { name: 'Goblet Squat or Barbell Squat', muscle_group: 'legs', target_sets: 3, target_reps: 9 },
      { name: 'Dumbbell Bench Press', muscle_group: 'chest', target_sets: 3, target_reps: 9 },
      { name: 'Lat Pulldown', muscle_group: 'back', target_sets: 3, target_reps: 9 },
      { name: 'Romanian Deadlift', muscle_group: 'legs', target_sets: 3, target_reps: 9 },
      { name: 'Seated Shoulder Press', muscle_group: 'shoulders', target_sets: 3, target_reps: 9 },
      { name: 'Cable Curl or Rope Pushdown', muscle_group: 'arms', target_sets: 3, target_reps: 11, target_sets_label: '2-3' },
    ],
  },
};

export const BROWSE_CATEGORIES = [
  { key: 'push', label: 'Push' },
  { key: 'pull', label: 'Pull' },
  { key: 'legs', label: 'Legs' },
  { key: 'chest', label: 'Chest' },
  { key: 'back', label: 'Back' },
  { key: 'shoulders', label: 'Shoulders' },
  { key: 'arms', label: 'Arms' },
  { key: 'glutes', label: 'Glutes' },
  { key: 'upper_body', label: 'Upper Body' },
  { key: 'lower_body', label: 'Lower Body' },
  { key: 'full_body', label: 'Full Body' },
];
